@startuml


:Set sampling and upload intervals;

:Set **Sensor** pins, labels and calibration factors;

:Initialize **Logger**;


repeat :Check connection
if (Connected to WiFi and MQTT broker) then (yes)
    if (Sampling interval passed) then (yes)
        :Read sensors;
        :Calculate physical quantities;
        :Calculate mean, stdev;
    else (no)
        :continue;
    endif

    if (Upload interval passed) then (yes)
        :Update JSON with mean, stdev;
        :Reset mean, stdev and counters;
        :Publish JSON to MQTT broker;
    else (no)
        :continue;
    endif

    :Keep MQTT connection alive;
else (no)
    :Try to connect;
endif

@enduml